name: Init Project

on: create
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "project_name is ${{ github.event.repository.name }}"