name: Auto Init Project

on: 
  check_run: 
    requested_action
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "project_name is ${{ github.event.repository.name }}"