name: Init Project

on: 
  workflow_dispatch:
    inputs:
      asdgdfhjgj:
        type: string
        description: 'Define project name'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.asdgdfhjgj }}"