name: Init Project

on: 
  workflow_dispatch:
    inputs:
      project_name:
        type: string
        description: 'Define project name'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "project_name is ${{ github.event.inputs.project_name }}"
          
  DeployDev:
    name: Deploy to Dev 
    ##if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: approvers
      url: "https://github.com/mrhatz/${{ github.event.inputs.project_name }}"
    steps:
      - name: Deploy
        run: echo I am deploying! 