name: Init Project 2

on: [create, fork]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }} project_name is ${{ github.event.inputs.project_name }}"
          
  create:
    name: Deploy to Dev 
    ##if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: approvers
      url: "https://github.com/mrhatz/${{ github.event.inputs.project_name }}"
    steps:
      - name: Deploy
        run: echo "echo" ###gh repo create mrhatz/${{ github.event.inputs.project_name }} -p mrhatz/template --private
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}